#!/usr/bin/env bash

##Nabbed off a neat stack exchange answer
#http://stackoverflow.com/questions/26791240/how-to-get-percentage-of-processor-use-with-bash

. panel_config

while true; do
	# Read /proc/stat file (for first datapoint)
	read cpu user nice system idle iowait irq softirq steal guest< /proc/stat
	
	# compute active and total utilizations
	cpu_active_prev=$((user+system+nice+softirq+steal))
	cpu_total_prev=$((user+system+nice+softirq+steal+idle+iowait))
	
	sleep "$upd_cpu"
	
	# Read /proc/stat file (for second datapoint)
	read cpu user nice system idle iowait irq softirq steal guest< /proc/stat
	
	# compute active and total utilizations
	cpu_active_cur=$((user+system+nice+softirq+steal))
	cpu_total_cur=$((user+system+nice+softirq+steal+idle+iowait))
	
	# compute CPU utilization (%)
	cpu_util=$((100*( cpu_active_cur-cpu_active_prev ) / (cpu_total_cur-cpu_total_prev) ))
	
	printf "C %s%%\n" "$cpu_util"
done
