#! /usr/bin/env bash
#
# Example panel for lemonbar

. panel_config

num_mon=$(bspc query -M | wc -l)

top_cmd="%{A:urxvt -e top:}"
e_c_s="%{A}"

while read -r line ; do
	case $line in
		C*)
			#cpu output
			cpu="%{B$c_0} ${line#?} %{B-}"
			;;
		R*)
			#ram output
			ram="%{B$c_0} ${line#?} %{B-}"
			;;
		S*)
			# clock output
			sys="%{F$c_f}%{B$c_0} ${line#?} %{B-}%{F-}"
			;;
		B*)
			#Battery output
			bat="%{F$c_f}%{B$c_0} ${line#?} %{B-}%{F-}"
			;;
		V*)
			#Volume output
			vol="%{F$c_f}%{B$c_0} ${line#?} %{B-}%{F-}"
			;;
		N*)
			#Network output
			net="%{F$c_f}%{B$c_0} ${line#?} %{B-}%{F-}"
			;;
		M*)
			#mpd output
			mpd="%{F$c_f}%{B$c_0} ${line#?} %{B-}%{F-}"
			;;
		T*)
			# xtitle output
			title="%{F$c_f}%{B$c_0} ${line#?} %{B-}%{F-}"
			;;
		W*)
			# bspwm's state
			wm=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					[mM]*)
						[ $num_mon -lt 2 ] && shift && continue
						case $item in
							m*)
								# monitor
								FG=$c_f
								BG=$c_0
								;;
							M*)
								# focused monitor
								FG=$c_f
								BG=$c_0
								;;
						esac
						wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc monitor -f ${name}:} ${name} %{A}%{B-}%{F-}"
						;;
					[fFoOuU]*)
						case $item in
							f*)
								# free desktop
								FG=$c_f
								BG=$c_0
								text=""
								;;
							F*)
								# focused free desktop
								FG=$c_f
								BG=$c_0
								text=""
								;;
							o*)
								# occupied desktop
								FG=$c_f
								BG=$c_0
								text=""
								;;
							O*)
								# focused occupied desktop
								FG=$c_f
								BG=$c_0
								text=""
								;;
							u*)
								# urgent desktop
								FG=$c_f
								BG=$c_0
								text=""
								;;
							U*)
								# focused urgent desktop
								FG=$c_f
								BG=$c_0
								text=""
								;;
						esac
						#wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc desktop -f ${name}:} ${name} %{A}%{B-}%{F-}"
						wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc desktop -f ${name}:} ${text} %{A}%{B-}%{F-}"
						;;
					[LTG]*)
						# layout, state and flags
						#wm="${wm}%{F$c_f}%{B$c_0} ${name} %{B-}%{F-}"
						;;
				esac
				shift
			done
			;;
	esac
	printf "%s\n" "%{l}${mpd}${vol}%{c}${wm}%{r}${net}${cpu}${ram}${bat}${sys}"
done
